DNA_RESIDUES = {"DA", "DT", "DC", "DG", "DI"}
RNA_RESIDUES  = {"A",  "U",  "C",  "G",  "I"}
WATER         = "HOH"
DISALLOWED_RESIDUES = {""}
DISALLOWED_LIGANDS = {"NAG"} #like sugars
NON_AA        = DNA_RESIDUES | RNA_RESIDUES | {WATER} | DISALLOWED_RESIDUES | DISALLOWED_LIGANDS
