[workspace]
channels = ["conda-forge"]
name = "toolkit-for-pdb"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"
rdkit = "*"
biopython = "*"

[pypi-dependencies]
rcsb-api = ">=1.7.1, <2"
typer = ">=0.12"
